apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log-analysis-app-monitor
  namespace: log-analysis-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: log-analysis-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: log-analysis-app-alerts
  namespace: log-analysis-app
  labels:
    release: prometheus
spec:
  groups:
  - name: log-analysis-app
    rules:
    - alert: HighErrorRate
      expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 5% for the last 5 minutes"
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile of response time is above 2 seconds for the last 5 minutes"
    - alert: HighCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{container="log-analysis-app"}[5m])) / sum(container_spec_cpu_quota{container="log-analysis-app"} / container_spec_cpu_period{container="log-analysis-app"}) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "CPU usage is above 80% for the last 5 minutes"
    - alert: HighMemoryUsage
      expr: sum(container_memory_usage_bytes{container="log-analysis-app"}) / sum(container_spec_memory_limit_bytes{container="log-analysis-app"}) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected"
        description: "Memory usage is above 80% for the last 5 minutes"
